name: Build and Release JAR

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]  # 添加标签触发条件
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Configure Maven settings
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 
                                      http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <profiles>
            <profile>
              <id>alfresco</id>
              <repositories>
                <repository>
                  <id>alfresco-public</id>
                  <url>https://artifacts.alfresco.com/nexus/content/groups/public</url>
                  <releases>
                    <enabled>true</enabled>
                  </releases>
                  <snapshots>
                    <enabled>true</enabled>
                  </snapshots>
                </repository>
                <repository>
                  <id>central</id>
                  <url>https://repo1.maven.org/maven2</url>
                </repository>
              </repositories>
              <pluginRepositories>
                <pluginRepository>
                  <id>alfresco-plugin-public</id>
                  <url>https://artifacts.alfresco.com/nexus/content/groups/public</url>
                </pluginRepository>
              </pluginRepositories>
            </profile>
          </profiles>
          <activeProfiles>
            <activeProfile>alfresco</activeProfile>
          </activeProfiles>
        </settings>
        EOF
        
    - name: Build with Maven
      run: |
        # 仅修改provided作用域为compile进行构建
        sed -i 's/<scope>provided<\/scope>/<scope>compile<\/scope>/g' pom.xml || true
        mvn clean package -DskipTests -Dmaven.test.skip=true
        
    - name: Store version
      id: version
      run: |
        # 从pom.xml提取版本号
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: alfresco-outlook-attachments-jar
        path: target/*.jar
        retention-days: 30

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build  # 依赖构建任务
    # 仅在创建标签时触发发布
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: alfresco-outlook-attachments-jar
          path: release-artifacts
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: |
            Alfresco Outlook Attachments Module
            Version: ${{ needs.build.outputs.version }}
          files: |
            release-artifacts/*.jar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
