name: Build and Release JAR

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
      
    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: alfresco-outlook-attachments-jar
        path: target/*.jar
        retention-days: 30
        
    # 可选：如果想要创建 Release，取消下面的注释
    # - name: Create Release
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: v${{ github.run_number }}
    #     release_name: Release v${{ github.run_number }}
    #     draft: false
    #     prerelease: false
    #     
    # - name: Upload Release Asset
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: target/alfresco-outlook-attachments-1.0.0.jar
    #     asset_name: alfresco-outlook-attachments-1.0.0.jar
    #     asset_content_type: application/java-archive
